// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkzcdafgdcsotcnmlmcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpremNkYWZnZGNzb3Rjbm1sbWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzOTc3MDksImV4cCI6MjA4ODk3MzcwOX0.BwpeCzRZbhgMWlBn6YovNtSFBvdiIMBygTOG3S_Q2_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // sessionStorage limits token exposure: cleared automatically when the tab
    // is closed, reducing the window for XSS-based token theft vs localStorage.
    storage: typeof window !== 'undefined' ? window.sessionStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});